version: "3.8"
services:
  postman:
    image: pstauffer/newman-htmlextra
    volumes:
      - ./collection:/etc/newman
      - ./report:/etc/report
    command:
      [
        "run",
        "postman-api.json",
        "--reporters",
        "cli,htmlextra",
        "--reporter-htmlextra-export",
        "/etc/report/report.html",
      ]
