name: Postman Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postman:
        image: pstauffer/newman-htmlextra
        volumes:
          - ./collection:/etc/newman
          - ./report:/etc/report
        options: --name=postman

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Postman Tests
        run: docker exec postman newman run postman-api.json --reporters cli,junit,htmlextra --reporter-junit-export /etc/report/report.xml --reporter-htmlextra-export /etc/report/report.html

      - name: Save Test Report Artifact
        uses: actions/upload-artifact@v2
        with:
          name: test-report
          path: report
